name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  display-softuni-username:
    
    runs-on: ubuntu-latest

    steps:
      - name: Display SoftUni username
        run: echo 'MarAnVal'

  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Repo init
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
     
  ui-tests:

    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Repo init
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependancies
      run: npm install  
    - name: Install playwright
      run: npx playwright install
    - name: Start App
      run: npm start&
    - name: Run ui tests
      run: npm run test:ui
